//
// Generate the icinga2 configuration listing the DNS zones to check.
// If the generated configuration differs from what is installed, replace it
// and reload icinga.
//

package main

import (
	"fmt"
	"log/slog"
	"os"
	"sort"
	"text/template"

	abmon "github.com/abundo/abmon/internal"
)

// Todo, move to config file
const (
	icingaZonesDestFile = "/etc/icinga2/conf.d/factum-zones.conf"
	icingaZonesTmpFile  = "/tmp/factum-zones.conf"
)

var icingaZoneHeader = `
# ===========================================================================
# Warning: do not edit this file, it is automatically generated and
# any changes will be lost when the file is recreated
# ===========================================================================

template Host "dns-host-unmanaged" {
  check_command = "dummy"
  vars.no_ping = true
  vars.dummy_state = 0
  vars.dummy_text = "Host check disabled"
}
template Service "dns-service" {
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 30s
}

# object HostGroup "DNS-propagation" {
object ServiceGroup "DNS-propagation" {
  display_name = "DNS-propagation"
  assign where host.vars.dns_check_propagation
}
#object HostGroup "DNS-gonemaster" {
object ServiceGroup "DNS-gonemaster" {
  display_name = "DNS-gonemaster"
  assign where host.vars.dns_check_gonemaster
}

apply Service "DNS-propagation" {
  import "dns-service"
  assign where host.vars.dns_check_propagation
  check_command = "passive"
  enable_active_checks = false
  enable_passive_checks = true
  check_interval = "10800"
}
apply Service "DNS-Gonemaster" {
  import "dns-service"
  assign where host.vars.dns_check_gonemaster
  check_command = "passive"
  enable_active_checks = false
  enable_passive_checks = true
  check_interval = "10800"
}
`

var icingaZoneTemplate = `
object Host "Zone - {{.Name}}" {
  import "dns-host-unmanaged"
  vars.dns_zone = "{{.Name}}"
  vars.dns_customer = "{{.Customer}}"
  vars.dns_dnsnode = {{.DnsNode}}
  vars.dns_check_propagation = {{.DnsCheckPropagation}}
  vars.dns_check_gonemaster = {{.DnsCheckGonemaster}}
}
`

// Generate the icinga2 zones configuration from the loaded config.
// If it differs from the installed file, replace it and reload icinga.
func generateIcingaZonesConf(config *abmon.ConfigFile) error {
	of, err := os.Create(icingaZonesTmpFile)
	if err != nil {
		return fmt.Errorf("error creating output file: %w", err)
	}
	defer of.Close()

	of.WriteString(icingaZoneHeader)

	for _, customer := range config.SortedCustomers {
		zones := config.Customers[customer]
		of.WriteString("# ====================================================================\n")
		of.WriteString("#   Customer ")
		of.WriteString(customer)
		of.WriteString("\n")
		of.WriteString("# ====================================================================\n")

		// Sort zone names for this customer
		zoneNames := make([]string, 0, len(zones))
		for _, zone := range zones {
			zoneNames = append(zoneNames, zone.Name)
		}
		sort.Strings(zoneNames)

		for _, zoneName := range zoneNames {
			zone := config.Zones[zoneName]
			tmpl, err := template.New("template").Parse(icingaZoneTemplate)
			if err != nil {
				slog.Error(fmt.Sprint("Error parsing icinga zone template:", err))
				continue
			}
			if err := tmpl.Execute(of, zone); err != nil {
				slog.Error(fmt.Sprint("Error executing icinga zone template:", err))
			}
		}
	}

	// Is there any changes in configuration?
	same, err := abmon.FileCmp(icingaZonesTmpFile, icingaZonesDestFile)
	if err != nil {
		same = false
	}

	if same {
		slog.Info("Icinga zones configuration unchanged")
		return nil
	}

	slog.Info(fmt.Sprintf("Copying new icinga zones configuration %s to %s", icingaZonesTmpFile, icingaZonesDestFile))
	if err := abmon.CopyFile(icingaZonesTmpFile, icingaZonesDestFile); err != nil {
		return fmt.Errorf("error copying new icinga zones configuration file: %w", err)
	}

	slog.Info("Reloading icinga2 configuration")
	abmon.ReloadIcinga()
	return nil
}
