package main

//
// This is NOT a check
//
// Create Icinga configuration with DNS zones to check
// If configuration has changed, reload icinga
//

import (
	"fmt"
	"log/slog"
	"os"
	"sort"
	"text/template"

	cmdbase "github.com/abundo/abmon/cmd"
	abmon "github.com/abundo/abmon/internal"
	"github.com/alecthomas/kong"
)

// Todo, move to config file
const (
	dest_file = "/etc/icinga2/conf.d/factum-zones.conf"
	tmp_file  = "/tmp/factum-zones.conf"
)

// Check CLI Options
type Opts struct {
	abmon.CheckOpts
}

var opts Opts
var config *abmon.ConfigFile

// ----- Service definition ------

var icingaZoneHeader = `
# ===========================================================================
# Warning: do not edit this file, it is automatically generated and
# any changes will be lost when the file is recreated
# ===========================================================================

template Host "dns-host-unmanaged" {
  check_command = "dummy"
  vars.no_ping = true
  vars.dummy_state = 0
  vars.dummy_text = "Host check disabled"
}
template Service "dns-service" {
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 30s
}

# object HostGroup "DNS-propagation" {
object ServiceGroup "DNS-propagation" {
  display_name = "DNS-propagation"
  assign where host.vars.dns_check_propagation
}
#object HostGroup "DNS-gonemaster" {
object ServiceGroup "DNS-gonemaster" {
  display_name = "DNS-gonemaster"
  assign where host.vars.dns_check_gonemaster
}

apply Service "DNS-propagation" {
  import "dns-service"
  assign where host.vars.dns_check_propagation
  check_command = "passive"
  enable_active_checks = false
  enable_passive_checks = true
  check_interval = "10800"
}
apply Service "DNS-Gonemaster" {
  import "dns-service"
  assign where host.vars.dns_check_gonemaster
  check_command = "passive"
  enable_active_checks = false
  enable_passive_checks = true
  check_interval = "10800"
}
`

// ----- Service zone definition ------
var icingaZoneTemplate = `
object Host "Zone - {{.Name}}" {
  import "dns-host-unmanaged"
  vars.dns_zone = "{{.Name}}"
  vars.dns_customer = "{{.Customer}}"
  vars.dns_dnsnode = {{.DnsNode}}
  vars.dns_check_propagation = {{.DnsCheckPropagation}}
  vars.dns_check_gonemaster = {{.DnsCheckGonemaster}}
}
`

func main() {
	var err error
	kong.Parse(&opts, kong.Name("create_icinga_zones_conf"), kong.Description("Generate the icinga2 config for DNS zone checks"), kong.Configuration(cmdbase.ConfigLoader))
	check, err := abmon.NewCheck(opts.CheckOpts)
	if err != nil {
		os.Exit(abmon.UNKNOWN)
	}
	config = check.Config // shortcut

	of, err := os.Create(tmp_file)
	if err != nil {
		slog.Error(fmt.Sprint("Error creating output file", err))
		panic(err)
	}
	defer of.Close()

	of.WriteString(icingaZoneHeader)

	for _, customer := range config.SortedCustomers {
		zones := config.Customers[customer]
		of.WriteString("# ====================================================================\n")
		of.WriteString("#   Customer ")
		of.WriteString(customer)
		of.WriteString("\n")
		of.WriteString("# ====================================================================\n")

		// Sort zone names for this customer
		zoneNames := make([]string, 0, len(zones))
		for _, zone := range zones {
			zoneNames = append(zoneNames, zone.Name)
		}
		sort.Strings(zoneNames)

		for _, zoneName := range zoneNames {
			zone := config.Zones[zoneName]
			tmpl, err := template.New("template").Parse(icingaZoneTemplate)
			if err != nil {
				slog.Info(fmt.Sprint("Error parsing template:", err))
			}
			err = tmpl.Execute(of, zone)
			if err != nil {
				slog.Info(fmt.Sprint("Error executing template:", err))
			}
		}
	}

	// Is there any changes in configuration?
	same, err := abmon.FileCmp(tmp_file, dest_file)
	if err != nil {
		same = false
	}

	if !same {
		slog.Info(fmt.Sprintf("Copying new configuration %s to %s\n", tmp_file, dest_file))
		err := abmon.CopyFile(tmp_file, dest_file)
		if err != nil {
			slog.Error(fmt.Sprint("Error copying new configuration file:", err))
		} else {
			slog.Info("Reloading icinga2 configuration")
			abmon.ReloadIcinga()
		}
	} else {
		slog.Info("Configuration unchanged")
	}
}
