package main

//
// This is NOT a check
//
// Create Icinga configuration with DNS zones to check
// If configuration has changed, reload icinga
//

import (
	"os"
	"sort"
	"text/template"

	abmon "github.com/abundo/abmon/internal"
	"github.com/alecthomas/kong"
	log "github.com/sirupsen/logrus"
)

// Todo, move to config file
const (
	dest_file = "/etc/icinga2/conf.d/factum-zones.conf"
	tmp_file  = "/tmp/factum-zones.conf"
)

// Check CLI Options
type Opts struct {
	abmon.CheckOpts
}

var opts Opts
var config *abmon.ConfigFile

// ----- Service definition ------

var icingaZoneHeader = `
# ===========================================================================
# Warning: do not edit this file, it is automatically generated and
# any changes will be lost when the file is recreated
# ===========================================================================

template Host "dns-host-unmanaged" {
  check_command = "dummy"
  vars.no_ping = true
  vars.dummy_state = 0
  vars.dummy_text = "Host check disabled"
}
template Service "dns-service" {
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 30s
}

# object HostGroup "DNS-propagation" {
object ServiceGroup "DNS-propagation" {
  display_name = "DNS-propagation"
  assign where host.vars.dns_check_propagation
}
#object HostGroup "DNS-zonemaster" {
object ServiceGroup "DNS-zonemaster" {
  display_name = "DNS-zonemaster"
  assign where host.vars.dns_check_zonemaster
}

apply Service "DNS-propagation" {
  import "dns-service"
  assign where host.vars.dns_check_propagation
  check_command = "passive"
  enable_active_checks = false
  enable_passive_checks = true
  check_interval = "10800"
}
apply Service "DNS-Zonemaster" {
  import "dns-service"
  assign where host.vars.dns_check_zonemaster
  check_command = "passive"
  enable_active_checks = false
  enable_passive_checks = true
  check_interval = "10800"
}
`

// ----- Service zone definition ------
var icingaZoneTemplate = `
object Host "Zone - {{.Name}}" {
  import "dns-host-unmanaged"
  vars.dns_zone = "{{.Name}}"
  vars.dns_customer = "{{.Customer}}"
  vars.dns_dnsnode = {{.DnsNode}}
  vars.dns_check_propagation = {{.DnsCheckPropagation}}
  vars.dns_check_zonemaster = {{.DnsCheckZonemaster}}
}
`

func main() {
	var err error
	kong.Parse(&opts, kong.Name("create_icinga_zones_conf"), kong.Description("Generate the icinga2 config for DNS zone checks"))
	check, err := abmon.NewCheck(opts.CheckOpts)
	if err != nil {
		os.Exit(abmon.UNKNOWN)
	}
	config = check.Config // shortcut

	of, err := os.Create(tmp_file)
	if err != nil {
		log.Panic("Error creating output file", err)
	}
	defer of.Close()

	of.WriteString(icingaZoneHeader)

	for _, customer := range config.SortedCustomers {
		zones := config.Customers[customer]
		of.WriteString("# ====================================================================\n")
		of.WriteString("#   Customer ")
		of.WriteString(customer)
		of.WriteString("\n")
		of.WriteString("# ====================================================================\n")

		// Sort zone names for this customer
		zoneNames := make([]string, 0, len(zones))
		for _, zone := range zones {
			zoneNames = append(zoneNames, zone.Name)
		}
		sort.Strings(zoneNames)

		for _, zoneName := range zoneNames {
			zone := config.Zones[zoneName]
			tmpl, err := template.New("template").Parse(icingaZoneTemplate)
			if err != nil {
				log.Println("Error parsing template:", err)
			}
			err = tmpl.Execute(of, zone)
			if err != nil {
				log.Println("Error executing template:", err)
			}
		}
	}

	// Is there any changes in configuration?
	same, err := abmon.FileCmp(tmp_file, dest_file)
	if err != nil {
		same = false
	}

	if !same {
		log.Infof("Copying new configuration %s to %s\n", tmp_file, dest_file)
		err := abmon.CopyFile(tmp_file, dest_file)
		if err != nil {
			log.Error("Error copying new configuration file:", err)
		} else {
			log.Info("Reloading icinga2 configuration")
			abmon.ReloadIcinga()
		}
	} else {
		log.Info("Configuration unchanged")
	}
}
